server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testing_generation
    password: root
    username: root
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    database: MYSQL
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        generate-ddl: true
        ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
